name: flutter_rollbar
description: A Rollbar integration for Flutter
version: 0.0.1
author: Diego Domingues<diego.domingues16@gmail.com>
homepage: https://github.com/ddomingues/flutter_rollbar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  stack_trace: ^1.9.3
  meta: ^1.1.6

dev_dependencies:

